package com.state.machine.spring.app.util;

public enum Events {
    SENT_CONFIGURATION_REQUEST_MESSAGE, RECEIVED_CONFIGURATION_DATA_MESSAGE,MESSAGE_SENT,POSITIVE_EOS_ACK_RECEVIED,POSITIVE_REQ_ACK_RECEVIED,FAILED_TO_DECODE_ETA
}
