spring:
  security:
    user:
      name1: user123
      name2: test123
      password: password
      role: USER
    admin:
      name: admin123
      password: password
      role: ADMIN
  application:
    name: spring-security
server:
  port: 8090
